# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-26 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=250)),
                ('job_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=250)),
                ('worker_phone', models.IntegerField()),
                ('worker_id', models.IntegerField()),
                ('worker_address', models.CharField(max_length=500)),
                ('worker_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Job')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Company'),
        ),
    ]
