# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-26 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180926_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company'),
        ),
    ]
