# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180926_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worker_farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Farm'),
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_salary',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_work_date',
            field=models.DateField(default='2018-1-1'),
        ),
    ]
