# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180927_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Farm'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_work_date',
            field=models.DateField(),
        ),
    ]
