# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 11:47
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_worker_worker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='media'),
        ),
    ]
