# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180927_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worker_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_end_time',
            field=models.DateField(default='2018-01-01'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='media'),
        ),
    ]
