# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180927_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_end_time',
            field=models.DateField(),
        ),
    ]
