# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-01 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20181001_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='item_note',
            field=models.CharField(default='ds', max_length=160),
        ),
    ]
