# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-01 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_warehouse_item_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyinvoice',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='buyinvoice',
            name='notes',
            field=models.TextField(default='ملاحظات', max_length=1200),
        ),
    ]
