# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-01 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20181001_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.CharField(max_length=260)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('notes', models.TextField(default='ملاحظات', max_length=1200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Supplier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='buyinvoice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='buyinvoice',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='BuyInvoice',
        ),
    ]
