# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-05 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_mainfinancemovement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainfinancemovement',
            old_name='month',
            new_name='mode',
        ),
    ]
