# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-06 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20181006_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellinvoice',
            name='price10',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='price2',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='price3',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='price4',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='price5',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='price6',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='price7',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='price8',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='price9',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='quantity10',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='quantity2',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='quantity3',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='quantity4',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='quantity5',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='quantity6',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='quantity7',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='quantity8',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='quantity9',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
