# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-06 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20181006_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellinvoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Client'),
        ),
    ]
