# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-06 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20181006_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellinvoice',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
