# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-06 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20181006_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellinvoice',
            name='price10',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
