# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-06 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20181006_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellinvoice',
            name='product2',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product2', to='app.Product'),
        ),
    ]
