# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-08 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0034_farmfinancemove'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_description', models.CharField(default='البيان', max_length=260)),
                ('invoice_description2', models.CharField(blank=True, default='البيان', max_length=260, null=True)),
                ('invoice_description3', models.CharField(blank=True, default='البيان', max_length=260, null=True)),
                ('invoice_description4', models.CharField(blank=True, default='البيان', max_length=260, null=True)),
                ('invoice_description5', models.CharField(blank=True, default='البيان', max_length=260, null=True)),
                ('invoice_description6', models.CharField(blank=True, default='البيان', max_length=260, null=True)),
                ('invoice_description7', models.CharField(blank=True, default='البيان', max_length=260, null=True)),
                ('invoice_description8', models.CharField(blank=True, default='البيان', max_length=260, null=True)),
                ('invoice_description9', models.CharField(blank=True, default='البيان', max_length=260, null=True)),
                ('invoice_description10', models.CharField(blank=True, default='البيان', max_length=260, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('quantity2', models.IntegerField(blank=True, default=1, null=True)),
                ('quantity3', models.IntegerField(blank=True, default=1, null=True)),
                ('quantity4', models.IntegerField(blank=True, default=1, null=True)),
                ('quantity5', models.IntegerField(blank=True, default=1, null=True)),
                ('quantity6', models.IntegerField(blank=True, default=1, null=True)),
                ('quantity7', models.IntegerField(blank=True, default=1, null=True)),
                ('quantity8', models.IntegerField(blank=True, default=1, null=True)),
                ('quantity9', models.IntegerField(blank=True, default=1, null=True)),
                ('quantity10', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.IntegerField(default=1)),
                ('price2', models.IntegerField(blank=True, default=1, null=True)),
                ('price3', models.IntegerField(blank=True, default=1, null=True)),
                ('price4', models.IntegerField(blank=True, default=1, null=True)),
                ('price5', models.IntegerField(blank=True, default=1, null=True)),
                ('price6', models.IntegerField(blank=True, default=1, null=True)),
                ('price7', models.IntegerField(blank=True, default=1, null=True)),
                ('price8', models.IntegerField(blank=True, default=1, null=True)),
                ('price9', models.IntegerField(blank=True, default=1, null=True)),
                ('price10', models.IntegerField(blank=True, default=1, null=True)),
                ('total', models.IntegerField(default=1)),
                ('date', models.DateField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='ملاحظات', max_length=1200)),
                ('source', models.CharField(default='الرئيسية', max_length=180)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Supplier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Product')),
                ('product10', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product10b', to='app.Product')),
                ('product2', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product2b', to='app.Product')),
                ('product3', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product3b', to='app.Product')),
                ('product4', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product4b', to='app.Product')),
                ('product5', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product5b', to='app.Product')),
                ('product6', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product6b', to='app.Product')),
                ('product7', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product7b', to='app.Product')),
                ('product8', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product8b', to='app.Product')),
                ('product9', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product9b', to='app.Product')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
