# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-09 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20181009_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_ID_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_ID_number',
            field=models.IntegerField(),
        ),
    ]
