# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-10 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20181009_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmfinancemove',
            name='cost',
            field=models.BooleanField(default=False),
        ),
    ]
