# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-14 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20181014_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
