# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-14 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20181015_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Type'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='da2en',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daily',
            name='maden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daily',
            name='total_da2en',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daily',
            name='total_maden',
            field=models.IntegerField(default=0),
        ),
    ]
