# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-14 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20181015_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Type'),
        ),
    ]
