# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-19 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_remove_farm_farm_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_company',
        ),
    ]
