# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-20 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_remove_job_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Farm'),
        ),
    ]
