# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-20 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20181020_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='is_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
