# Generated by Django 2.1.2 on 2018-10-20 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_buyinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyinvoice',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Farm'),
        ),
    ]
