# Generated by Django 2.1.2 on 2018-10-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_auto_20181021_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyinvoice',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
