# Generated by Django 2.1.2 on 2018-10-20 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20181021_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Supplier')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Farm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
    ]
