# Generated by Django 2.1.2 on 2018-10-20 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_sellinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellinvoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Client'),
        ),
    ]
