# Generated by Django 2.1.2 on 2018-10-31 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20181021_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='category',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='type',
        ),
        migrations.AddField(
            model_name='daily',
            name='da2en_from_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='da2en_from_cat', to='app.Category'),
        ),
        migrations.AddField(
            model_name='daily',
            name='da2en_from_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='da2en_from_type', to='app.Type'),
        ),
        migrations.AddField(
            model_name='daily',
            name='maden_from_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
        migrations.AddField(
            model_name='daily',
            name='maden_from_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Type'),
        ),
    ]
