# Generated by Django 2.1.2 on 2018-10-31 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20181031_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='da2en_from_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='da2en_from_cat', to='app.Category'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='da2en_from_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='da2en_from_type', to='app.Type'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='maden_from_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='maden_from_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Type'),
        ),
    ]
