# Generated by Django 2.1.2 on 2018-10-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_auto_20181031_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='total_da2en',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='total_maden',
        ),
    ]
