# Generated by Django 2.1.2 on 2018-11-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_auto_20181102_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_ID_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_mob_number',
            field=models.CharField(max_length=12),
        ),
    ]
