# Generated by Django 2.1.2 on 2018-11-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_auto_20181102_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_ID_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_mobile_number',
            field=models.CharField(max_length=12),
        ),
    ]
