# Generated by Django 2.1.2 on 2018-11-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_auto_20181102_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mezan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da2en', models.IntegerField(default=0)),
                ('maden', models.IntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
    ]
