# Generated by Django 2.1.2 on 2018-11-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='company',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='activation',
            name='serial1',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='activation',
            name='serial2',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
