# Generated by Django 2.2 on 2019-04-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_auto_20181115_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellinvoice',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellinvoice',
            name='unpaid',
            field=models.IntegerField(default=0),
        ),
    ]
