# Generated by Django 2.2 on 2019-04-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_auto_20190430_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
