# Generated by Django 2.2 on 2019-04-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_daily_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='paid',
            field=models.IntegerField(),
        ),
    ]
