# Generated by Django 2.2 on 2019-05-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0087_auto_20190430_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_balance',
            field=models.IntegerField(default=0),
        ),
    ]
